### ISSUE TITLE
Color Gen issue

### ISSUE THREAD

**Issue by ParvinderjitSF** [FlutterGen/flutter_gen#107]
I got stuck if I have mentioned more than one color in colors.xml file it is not updating the colors.gen.dart. Works fine if there is only one color in the file

**Comment by lcdsmao** [comment]
Hi @ParvinderjitSF.
Could you please provide some example code?

**Comment by ParvinderjitSF** [comment]
Hi @Icdsmao It was my bad there was an error in colors.xml file.
This was the error build_runner returning me.
<img width="705" alt="Screenshot 2021-05-19 at 11 07 56 PM" src="https://user-images.githubusercontent.com/37068931/118858711-13969280-b8f7-11eb-8ca8-63d8a2eb9ee7.png">

I wasn't able to understand the error which build runner returning event I haven't noticed that it is giving me an error. But later I got the error in xml file. Actually forgot to add the resource element. <resource> <colors> </colors> </resource>. If I'm adding single <color> </color> then it is working fine but as soon as I am entering multiple like

<colors> </colors>
<colors> </colors> 

and it stoped working. It have to be as it is not a valid xml. I think this Closure: () => String from Function 'toString':.: Expected end of input at 2:5 error not clearing which file have error. I think this error message can be more meaningful

**Comment by ParvinderjitSF** [comment]
Closing this issue as it was due to xml file issue
