### ISSUE TITLE
Load ImageAsset for different module

### ISSUE THREAD

**Issue by Izudinalqasam** [FlutterGen/flutter_gen#133]
I have a problem when load asset generated in one module and it can be accessed in another module. i have read generated file but not found to set package for assetimage

currently i using path generated image and making AssetImage from the path.

`AssetImages(
                  Assets.image.widgets.textDialogBox.textDialogBoxImage.path, package: "myPackage")`

**Comment by lcdsmao** [comment]
Hi @Izudinalqasam 
Sorry for the lack of documentation.
Have you tried setting `package_parameter_enabled`?
```
flutter_gen:
  assets:
    package_parameter_enabled: true
```

https://github.com/FlutterGen/flutter_gen/blob/main/README.md#default-configuration
