### ISSUE TITLE
Requires parameters to exclude directories.

### ISSUE THREAD

**Issue by wasabeef** [FlutterGen/flutter_gen#170]
Please consider the following use-case:

```
assets/images/... -> should be generated
assets/data/... -> should not be generated
```

All files inside the data folder are simple data files, for example json or xml files. Which are used internally in the flutter application and therefore should not be considered as layout files (images, color, fonts etc.).

It would be great to have an `exclude: ` property to defines those files or directories.

_Originally posted by @jayjah in https://github.com/FlutterGen/flutter_gen/issues/132#issuecomment-986102743_

**Comment by Aristidios** [comment]
Is it possible to generate all assets without specifying many paths - it gets complicated when your assets are nested in multiple folders ?

**Comment by vominhkhoi92** [comment]
Is it possible? Please help if it could be.

> Is it possible to generate all assets without specifying many paths - it gets complicated when you have many assets nested in multiple folders in your `assets/` directory

**Comment by dev-shvetsov** [comment]
Any updates?

**Comment by AlexV525** [comment]
@AlexSeednov It is likely that you've put `assets/font/` in your assets list. Remove them and your result will be as you desired.

**Comment by AlexV525** [comment]
Using those fonts in your application does not require you to write them in the assets list. Example: https://github.com/FlutterGen/flutter_gen/blob/584648dfdcb16fcfc937004e142201340518a9db/examples/example/pubspec.yaml#L74

**Comment by AlexV525** [comment]
@AlexSeednov See https://github.com/FlutterGen/flutter_gen/issues/509#issuecomment-2169090864 and #529.
