### ISSUE TITLE
[Feature Request]Make AssetGenImage class callable

### ISSUE THREAD

**Issue by soumyamahunt** [FlutterGen/flutter_gen#183]
By making `AssetGenImage` [callable](https://dart.dev/guides/language/language-tour#callable-classes), instead of writing `Assets.images.profile.image()` we can write `Assets.images.profile()`. Will be happy to create a PR on this:)

**Comment by AlexV525** [comment]
This does seem to be helpful to the readability of generated and usage codes. Please stick with `image()` for now.
