### ISSUE TITLE
[Feature Request]  Autogenerate List with assets in class

### ISSUE THREAD

**Issue by jamesblasco** [FlutterGen/flutter_gen#186]
We have around 50 icons in our app and we would like to autogenerate a value getter that returns a list of all the assets in the class

```dart
class $AssetsIconsGen {
  const $AssetsIconsGen();

  /// File path: assets/icons/arrow_down.svg
  SvgGenImage get arrowDown => const SvgGenImage('assets/icons/arrow_down.svg');

  /// File path: assets/icons/arrow_left.svg
  SvgGenImage get arrowLeft => const SvgGenImage('assets/icons/arrow_left.svg');

  List<SvgGenImage> get svgAssets =>  [arrowDown, arrowLeft];
}
```
The reason is that we have an internal design component library app that displays all the icons together

**Comment by vsly-ru** [comment]
Also looking for this feature!
In our project we have 100+ icons and I want a page with a list of currently imported icons with its names.
Looking thru files is not always an option or a convenient one for svg on macOS (you basically have to convert em all to PNGs to view adequately sized previews).
'dart:mirrors' is no longer available, so it's hard to simply list all available fields of a class.
So it would be a perfect solution to have an option in flutter_gen itself (or as a default behaviour) to also generate a list while there.

**Comment by JulianBissekkou** [comment]
@wasabeef any updates on this feature or the PR?

**Comment by AlexV525** [comment]
> It's then a bit harder to find unused assets.

How would that be? Simply excludes usages in the same file can obtain accurate result.

**Comment by Nico04** [comment]
> Simply excludes usages in the same file can obtain accurate result.

This is not a direct operation, it's IDE dependant. Moreoever it adds generated code that it's not necessary for some projects.
Adding a simple parameter in the yaml would fulfill everyone's need, don't you think ?

**Comment by AlexV525** [comment]
> This is not a direct operation, it's IDE dependant. Moreoever it adds generated code that it's not necessary for some projects.

Did it cause something to misbehave in your project? Please share if you have any other concerns.

> Adding a simple parameter in the yaml would fulfill everyone's need, don't you think ?

Not always. The balance between flexibility and maintenance is a great study course.

**Comment by Nico04** [comment]
> Not always. The balance between flexibility and maintenance is a great study course.
I see, then forget my needs, I'll find my own way ;)
