### ISSUE TITLE
how to get only String for image

### ISSUE THREAD

**Issue by samithe7** [FlutterGen/flutter_gen#195]
now i get  
```dart
   static const AssetGenImage imagesChip1 = 
       AssetGenImage('assets/images/chip1.jpg'); 
```

i want this
```dart
 static const String imagesChip1 = 
       'assets/images/chip1.jpg'; 
```

if  image path string  is   AssetGenImage  i can't  make the widget  const

**Comment by Abhishek01039** [comment]
Hello @samithe7 
you can try like this `Assets.images.imagesChip1.path`

**Comment by samithe7** [comment]
> 

thanks but i  want  make the widget const . if i use  Assets.images.imagesChip1.path  widget don;t be const .

**Comment by lcdsmao** [comment]
We should consider adding an option to toggle this just like svg_intergation.
Currently, how about making your widget path nullable:
```dart
class MyWidget extends StatlessWidget {
  const MyWidget(this.path);

  final String? path;

  Widget build(BuildContenxt context) {
    final effectivePath = path ?? 'default_path';
    return ...;
  }
}
```
This pattern is also common in flutter.

**Comment by samithe7** [comment]
```dart
now i get  assets.gen.dart file

   static const AssetGenImage imagesChip1 = 
       AssetGenImage('assets/images/chip1.jpg'); 
Is there any way  in assets.gen.dart file only get String    like this

 static const String imagesChip1 = 
       'assets/images/chip1.jpg';
```

**Comment by Hwan-seok** [comment]
@lcdsmao I think the main goal of @samithe7 (also me) is making the Image widget as const.
How about providing an option to generate assets separately?

e.g)
TO-BE
```dart

class AssetImages {
  static const avatar = AssetGenImage('assets/images/avatar.png');
  ...
}
class AssetFonts{
  ...
}

```

AS-IS
```dart
class Assets {
  Assets._();

  static const $AssetsFontsGen fonts = $AssetsFontsGen();
  static const $AssetsImagesGen images = $AssetsImagesGen();
}
  ```

**Comment by lcdsmao** [comment]
@Hwan-seok 
You can generate const via setting the `flutter_gen.assets.style`.
https://github.com/FlutterGen/flutter_gen/issues/185#issuecomment-1006183927

**Comment by Hwan-seok** [comment]
Yes, I am aware of that.
But the whole assets are in the one class named `Assets` and the subcategory `image` is in the property name.
The reason why we are using `.` separated style is that it divides the asset categories greatly.
It will be great if they are separated as follows.
```dart
AssetImages.chip1
AssetJsons.accounts
AssetLotties.fire
```
