### ISSUE TITLE
Error: No named parameter with the name 'theme'

### ISSUE THREAD

**Issue by thanhbinh84** [FlutterGen/flutter_gen#203]
I am using the latest build to generate code, it shows the error below 

![Screen Shot 2022-03-11 at 17 18 42](https://user-images.githubusercontent.com/100809857/157853423-81d26637-98e8-48d2-8368-5fb44e947bb3.png)

I have to go to `assets.gen.dart` file, remove `theme` line to make it works. 

I am using flutter_svg: ^1.0.3

**Comment by lcdsmao** [comment]
Hi @thanhbinh84 
From the error message, it seems you are using flutter_svg-0.23.0+1.
The `theme` property is supported in flutter_svg-1.0.3:
https://pub.dev/documentation/flutter_svg/latest/svg/SvgPicture/SvgPicture.html

**Comment by thanhbinh84** [comment]
Yeah, that's true. There is problem with pub cache, I increased the version but still...
Thank you.
