### ISSUE TITLE
How to quickly find unused resources and delete them ？

### ISSUE THREAD

**Issue by OHeroJ** [FlutterGen/flutter_gen#211]
Some resources are no longer used, but they are not deleted immediately, how can I quickly find out later？

Can you provide an interface for discovering unused resources and quickly deleting them?

just like:

```shell
# show unused assets
$ fluttergen assets unused --list 
assets/images/a.png
assets/images/b.png

# delete unused assets 
$ fluttergen assets delete assets/images/a.png
$ fluttergen assets delete --all
```

I think this is a very useful and common feature, do you agree? expect to be fulfilled！

**Comment by AlexV525** [comment]
Try https://pub.dev/packages/delete_un_used_assets.
