### ISSUE TITLE
Json support, Json to translation strings

### ISSUE THREAD

**Issue by Tkko** [FlutterGen/flutter_gen#224]
Hi, thanks for the package.

I'm using Json file to store translation strings:
```
{
  "appTitle": "Title",
  "continueButton": "Continue"
}
```
And I want to generate `Strings` class from it

```
class Strings {
  const Strings._();

  static const appTitle = 'appTitle';
  static const continueButton = 'continueButton';
}
```

**Comment by AlexV525** [comment]
This should be covered by Flutter's localization tool. There is no plan for us to create the same functionality.
