### ISSUE TITLE
Upgrade XML

### ISSUE THREAD

**Issue by TheHypnoo** [FlutterGen/flutter_gen#232]
Hi, I have updated flutter_svg and I found that flutter_gen has a lower version of the xml, so it does not let me use the latest version of flutter_svg.

Is there any way to fix it?

Could flutter_gen be updated to the latest version?

**Comment by HudsonAfonso** [comment]
+1

**Comment by wasabeef** [comment]
I'm still wondering what to do because many plugins depend on xml ^5.x.x. 🤔
