### ISSUE TITLE
error when png name is start with number

### ISSUE THREAD

**Issue by hello-soon** [FlutterGen/flutter_gen#250]
assets/images/olp/2.png

<img width="804" alt="image" src="https://user-images.githubusercontent.com/62131847/171881449-796a9edd-aa7d-48c6-b55a-21e69284f346.png">

**Comment by Linkadi98** [comment]
you have to rename image file to `image1` or something not start with a number because dart doesn't allow that

**Comment by DevNico** [comment]
I don't think this should error though. By default it should either be ignored / warned about in the build runner output or replace any invalid characters with e.g. an `_` as well as prepend it with an `_` if required.

**Comment by freshtechtips** [comment]
> you have to rename image file to `image1` or something not start with a number because dart doesn't allow that

Is it a good idea if the package provided a handling for this case??

**Comment by Linkadi98** [comment]
> > you have to rename image file to `image1` or something not start with a number because dart doesn't allow that
> 
> 
> 
> Hi, is it a good idea if the package provided a handling for this case??

I think the package should do what it does, this issue is depended on us IMO. The package only should show specific error to us and has nothing to do with this issue.

**Comment by bramp** [comment]
I tried to fix this, and just naming issues here: https://github.com/FlutterGen/flutter_gen/pull/433. Just waiting for a review
