### ISSUE TITLE
Cannot generate file with custom class_name

### ISSUE THREAD

**Issue by klnfreedom** [FlutterGen/flutter_gen#297]
Hello everyone! Please explain why I can't generate a file with a custom classAssetName. Anyway, the library will generate a class with the Asset name instead CoreAssets.
my environment: 
- flutter 3.3.2, dart 2.18.1;
- flutter_gen_runner: ^4.3.0
- build_runner: ^2.2.1

My example in the pubspec.yaml:
> flutter_gen:
>   output: lib/generated/assets/
>   line_length: 100
> 
>   assets:
>     enabled: true
>     outputs:
>       class_name: CoreAssets

**Comment by klnfreedom** [comment]
And I've downloaded your example folder from flutter_gen, and there is the same issue

**Comment by wasabeef** [comment]
@klnfreedom This feature will be added starting with v5.0.0 (this week). Sorry I'll fix the README.

**Comment by klnfreedom** [comment]
Okay, thx!

**Comment by klnfreedom** [comment]
Thank you so much! Everything is working
