### ISSUE TITLE
LottieGenImage.lottie ignores the `controller` argument (5.0.1)

### ISSUE THREAD

**Issue by noinskit** [FlutterGen/flutter_gen#308]
The autogenerated `LottieGenImage` takes `Animation<double>? controller` as argument, but it just ignores it instead of passing it to `Lottie.asset()`.

**Comment by wasabeef** [comment]
Thank you for the report.

**Comment by wasabeef** [comment]
@noinskit 
I just released `v5.0.2` its fixed the bug.
