### ISSUE TITLE
[FR]: Support for Flutter Web

### ISSUE THREAD

**Issue by hogdamian** [FlutterGen/flutter_gen#334]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

Hello,

just wanted to ask if its planned to support Flutter Web Support.

### Describe the solution

This package makes implementing assets so easily and nice, this comfort would be great on Flutter Web.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wasabeef** [comment]
@hogdamian 

I added sample codes for the web.
