### ISSUE TITLE
[FR]: Support for vector_graphic directly

### ISSUE THREAD

**Issue by mcssym** [FlutterGen/flutter_gen#362]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

Flutter SVG is not optimized enough when loading many svg with no possibility to cache image at startup easily.

### Describe the solution

Integrate vector_graphic in the generation process alongside flutter_svg and allow to user to configure vector_graphic as we configure flutter_svg currently. And therefore add the generation of the `.vec` optimized file of the SVG in the process of generation of the differents assets dart file with the supports of VectorGraphic widget instead of SvgPicture.

### Additional context

flutter_svg already used vector_graphic under the hood and recommend to use the `.vec` generated binary file when more optimization is needed. So it'll be cool if this package directly allows it.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by powdream** [comment]
I made a pull-request to address this feature request.

**Comment by powdream** [comment]
I closed my pull request to address this issue.

**Comment by raldhafiri** [comment]
@powdream I have create a new pull request to solve the issue
