### ISSUE TITLE
[FR]: Not getting full path in json generated file

### ISSUE THREAD

**Issue by hacodeszignuts** [FlutterGen/flutter_gen#388]
### Is there an existing issue for this?

- [X] me have searched the existing issues

### Describe the problem

You're package is too good. but there is small issue. When me generated json file tan file generated same as image asset file but file path is like : 'assets/json/map_style.json' in $AssetsJsonGen class. So me need full path. 

### Describe the solution

me reviewed the package and In other asset class there is keyname like : 
"" String get keyName => 'packages/superapp_assets/$_assetName'; ""

So if you can generate keyname in json classes so it'll be solve the issues.

But me just get the temporary solution like this :- 
"" '${MySuperAppAssets.images.camera.keyName.split('/assets').first}/${MySuperAppAssets.json.mapStyle}' ""

it's not the proper solution but me don't do this then i need to give a path whenever me generated assets. So, Hope you'll fix this one or add this feature

### Code of Conduct

- [x] me agree to follow this project's Code of Conduct

**Comment by AlexV525** [comment]
Could you provide a reproducible example? The comment doesn't seem to explain the problem well.

**Comment by hacodeszignuts** [comment]
Your reply is too late, and the issue is already resolved.
