### ISSUE TITLE
Feature Request: Support for MaterialAccentColor

### ISSUE THREAD

**Issue by nicodumdum** [FlutterGen/flutter_gen#39]
First of all, definitely loving this generator. ❤
But if I may be allowed to request for a feature, please add support for [MaterialAccentColor.](https://api.flutter.dev/flutter/material/MaterialAccentColor-class.html) 🙏🥺

Thanks! 😄

**Comment by lcdsmao** [comment]
Hi @nicodumdum.
Thank you for using FlutterGen and your suggestion.
We will add support for MaterialAccentColor in the next release. 😀
