### ISSUE TITLE
[BUG]:  how to change the color property of generated svg file

### ISSUE THREAD

**Issue by mayur-mindstack** [FlutterGen/flutter_gen#396]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Command type

build_runner (Default)

### What happened?

when i tried Assets.icons.homeIcon.svg(color: );

its showing 'color' is deprecated and shouldn't be used

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lcdsmao** [comment]
You should use colorFilter instead.
