### ISSUE TITLE
[FR]: Add ignore property to options file

### ISSUE THREAD

**Issue by ivan-dubovenko-m10** [FlutterGen/flutter_gen#397]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

We are using mason to generate template of packages to out app and put .gitkeep to assets folder.

In generated asset file we see:

```dart
static const String gitkeep = 'assets/.gitkeep';
```

### Describe the solution

It will be nice if will be option to ignore files:
```yaml
ignore:
  - "**/.gitkeep"
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by anchao-lu** [comment]
same fr

**Comment by dev-shvetsov** [comment]
AnyUpdates?

**Comment by AlexV525** [comment]
Use `excludes` under the `flutter_gen > assets`. See https://github.com/FlutterGen/flutter_gen/blob/main/README.md#excluding-generating-for-assets.
