### ISSUE TITLE
[FR]: Include image dimensions (and perhaps other metadata) in generated AssetGenImage class

### ISSUE THREAD

**Issue by bramp** [FlutterGen/flutter_gen#402]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

At runtime I would like to know the dimension of the assets, and perhaps other metadata, without parsing the file.

Today, I can do something like (taken from [StackOverflow](https://stackoverflow.com/a/65096977/88646)):

```dart
final Image image = Image(image: AssetImage('assets/images/someimage.png'));
Completer<ui.Image> completer = new Completer<ui.Image>();
    image.image
        .resolve(new ImageConfiguration())
        .addListener(new ImageStreamListener((ImageInfo image, bool _) {
      completer.complete(image.image);
    }));
ui.Image info = await completer.future;
print("${info.width} x ${info.height};
```

### Describe the solution

I'd prefer to do:

```dart
print(Assets.images.someimage.size)
```

The size param would be constant, and avoid any kind of async processing.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sarbazx** [comment]
Hello, 

this is not working, added `parse_metadata: true` under flutter_gen in pubspec.yaml, still size is not added, does the aforementioned work have been added to latest version (5.4.0)?

**Comment by AlexV525** [comment]
> does the aforementioned work have been added to latest version (5.4.0)?

No.
