### ISSUE TITLE
generated output folder name not being respected

### ISSUE THREAD

**Issue by SerggioC** [FlutterGen/flutter_gen#42]
Setting **flutter_gen** as the output folder name, the generated folder name is always **gen/**
```
flutter_gen:
  output: lib/flutter_gen/
```

Can you solve this? Thanks!

**Comment by wasabeef** [comment]
@SerggioC 
Thank you for your report.
Just released the fixed version that.

**Comment by SerggioC** [comment]
That worked. Thanks for the quick fix!

**Comment by orestesgaolin** [comment]
One important thing is that the provided output needs to exist before running. If there's no `flutter_gen` folder, then the tool will use default `gen` either way
