### ISSUE TITLE
Future Request : Support other file format like flr

### ISSUE THREAD

**Issue by cenumi** [FlutterGen/flutter_gen#46]
I notice ".flr" file used by flare_flutter is not generated.
This package is widely used to add animation to flutter apps, just like lottie from Airbnb.
version 1.2.1 by dart command-line.

Thank you very much.😀

**Comment by wasabeef** [comment]
@cenumi 
We just released 1.3.0. 
It generates correctly for Flare and other files.
And supports the flare_flutter.

Plase use it,
```shell
$ brew upgrade fluttergen/tap/fluttergen
```

```shell
$ dart pub global activate flutter_gen
```
