### ISSUE TITLE
Feature Request: Lottie files

### ISSUE THREAD

**Issue by vintage** [FlutterGen/flutter_gen#47]
Hey there!

Would be great to have integration for the lottie files (through https://pub.dev/packages/lottie). Right now in the project I'm working on we're using the syntax:

```
Lottie.asset(Assets.animations.animationName)
```

but would be lovely to achieve it just like for the SVG files through the generated code:

```
Assets.animations.animationName.lottie()
```

The trickiest part would be probably to distinguish lottie files from non-lottie files, as it uses `.json` as the file extension?

**Comment by jamesblasco** [comment]
@wasabeef would you be interested in a PR for this. I am using flutter_gen in a project and I would like to generate lottie assets with it.

I think the implementation is almost straight forward, the only thing is the file extension .json is very vague. I was thinking to only support files with the name `*_lottie.json`. What do you think about it?

**Comment by nguyenvinhtien28** [comment]
> @wasabeef would you be interested in a PR for this?. I am using flutter_gen in a project and I would like to generate lottie assets with it.
> 
> I think the implementation is almost straight forward, the only thing is the file extension .json is very vague. I was thinking to only support files with the name `*_lottie.json`. What do you think about it?

I think it's a good idea.
Please implement  it.

**Comment by bramp** [comment]
This issue has been fixed ~a year ago. 

As for https://github.com/FlutterGen/flutter_gen/issues/47#issuecomment-966241081 the [implementation](https://github.com/FlutterGen/flutter_gen/blob/390e1a6fa938961437f8bad78185a670dd8d9e58/packages/core/lib/generators/integrations/lottie_integration.dart#L112-L120) finds all `.json` files that contain a json object with specific keys and a version of > 4.4.0. This can still lead to false positives, but seems rare.
