### ISSUE TITLE
[FR]: Support getting filename

### ISSUE THREAD

**Issue by JankLai** [FlutterGen/flutter_gen#482]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

In my case I want to get the asset file name, and I see he "path" attribute of `AssetGenImage` class is always the absolute path of file, there isn't an attribute for the file name.

### Describe the solution

Add a new attribute for the asset file name, not the absolute path of file.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bramp** [comment]
Why not just do this yourself with `basename(asset.path)` ? Or create an extension on AssetGenImage, eg:

```dart
extension AssetGenImageExt on AssetGenImage {
  String get filename => basename(path);
}
```

(This was written on my phone, so might have errors)

**Comment by AlexV525** [comment]
We don't have a plan to extend fields like this, we also might want to keep generated data clean & straight. So I'm going to close this as won't fix. Feel free to write extensions on generated classes.
