### ISSUE TITLE
[FR]: Support for lottie zip archives

### ISSUE THREAD

**Issue by RTAzis** [FlutterGen/flutter_gen#495]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

The current package supports Lottie JSON files. Lottie itself also supports ZIP archives where the archive and the JSON file inside have the same name convention. I propose adding support for these ZIP archives for enhanced functionality.
```Dart
// Load an animation and its images from a zip file
Lottie.asset('assets/my_lottie_files/test.zip'),
```

### Describe the solution

When `lottie: true`, it may loop through ZIP archives, unpack them into memory, detect .json files, and validate their signature.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AlexV525** [comment]
Zips can have various of usages. Expanding the zip with Lottie seems out of the scope of the library. To use a zip with Lottie, as an alternative, `Lottie.asset(MyAssets.myLottieFiles.test)` should be fit for the case.

Feel free to leave more comments.
