### ISSUE TITLE
[FR]: dotLottie support

### ISSUE THREAD

**Issue by josh-burton** [FlutterGen/flutter_gen#505]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

dotLottie is compressed lottie file format that would be great to support

### Describe the solution

Support the file format

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AlexV525** [comment]
Could you provide the spec of the format and a use case that how Lottie in Flutter uses that format?

**Comment by dungngminh** [comment]
This is document of dotLottie from Lottie: https://lottiefiles.notion.site/Getting-started-with-dotLottie-907cb7b157b34990a7bba7bcae8f21b0

As mentioned in this document, dotLotties is allowing for considerably smaller animation files compared to JSON. It makes Lottie animation file size smaller than JSON and has some benefits in Lottie Development and Design.

[lottie](https://pub.dev/packages/lottie) package currently supports dotLottie from 3.0.0, I think flutter_gen currently supports .zip and hopefully will support dotLotties ASAP.

**Comment by AlexV525** [comment]
Looks like we can accept the `.lottie` extension as an easy approach.

**Comment by dungngminh** [comment]
Make sense! f you can accept it as an easy approach, I think we should add more docs / notes for require some extra definition attention

**Comment by dungngminh** [comment]
`decoder` basically is a parameter of `Lottie`, it need to be provided `customDecoder` for `.lottie` file is must do, developers must read documentation and know it before implementation.
