### ISSUE TITLE
[FR]: Support Asset Transformation

### ISSUE THREAD

**Issue by josh-burton** [FlutterGen/flutter_gen#514]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

Flutter 3.22.0 now supports asset transformation. This allows, for example a .svg to be transformed into a .vec.

https://docs.flutter.dev/ui/assets/asset-transformation

### Describe the solution

Support a way to generate asset classes that point to the transformed asset rather than the raw asset

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AlexV525** [comment]
As examples are shown in the doc, resolving how transformers handled assets would be overwhelming. To use the asset in different loaders with flutter_gen, simply use its path should be able to compatible with Asset Transformations. In this case, the package will not add additional support for the feature. Feel free to add inputs to my opinion.

**Comment by AlexV525** [comment]
Closing as above suggestion. Feel free to leave any further thoughts in the thread.

**Comment by Cgende** [comment]
I think this should be reopened. The proposed solution:

>  simply use its path should be able to compatible with Asset Transformations

Isn't possible because flutter_gen can't parse the pubspec.yaml when using asset transformations. It gives an error:
`There is a problem with "assets". type 'YamlMap' is not a subtype of type 'String' in type cast`

This is similar to #494.

**Comment by AlexV525** [comment]
> This is similar to #494.

So let's track the on that issue, thanks for the reference.

**Comment by myxzlpltk** [comment]
Yes, that error blocking the code generation. Its okay if fluttergen cannot generate that. I still can call direct path
