### ISSUE TITLE
Discussion of renaming FlutterGen?

### ISSUE THREAD

**Issue by wasabeef** [FlutterGen/flutter_gen#53]
Please read this https://github.com/FlutterGen/flutter_gen/issues/49.

This package has exactly the same name as the official Flutter Localization package, so there is a name conflict. Therefore, the official L10n (Flutter 1.22 +) and build_runner of FlutterGen cannot be used at the same time.
***Dart CLI and Homebrew are fine.**

We now have these options available. 
- Just minor change the [pub.dev namespace](https://pub.dev/packages/flutter_gen) =>  😄
- Don't support build_runner => 🎉  
- Rebranding and re-register to pub.dev (...  need ideas..) => 🚀

Please vote...

**Comment by vintage** [comment]
Ideally we should support the `build_runner` - using it in all the projects to perform auto generations provided by few other libs (like `freezed` or `json_serializable`). Appreciate the fact that all of the generation can be done by simply calling `build_runner` and no additional steps are required in the CI config (even if it's only about adding one new call).

As the `flutter_gen` is about assets generation, maybe ... `genset`?

**Comment by dudeck** [comment]
I'm also totally for changing the name of this library. I think it will be the easiest and proper solution with no error prones.

**Comment by mark-apn** [comment]
In favor of renaming and republishing:

Names for inspiration:
- assets_gen
- safe_assets
- r_flutter (For those who are used to the R file in Android development)
- type_safe_assets

**Comment by andreadelfante** [comment]
r_flutter would be a great name! 😄

**Comment by wasabeef** [comment]
@vintage @dudeck @mark-apn @andreadelfante and guys.

I'm sorry for the late reply and decisions.

We decided how solves it.

**for commands**
```
$ brew install FlutterGen/tap/fluttergen
or
$ dart pub global activate flutter_gen

$ fluttergen -c pubspec.yaml
```


**for build runner**
```yaml
dev_dependencies:
  build_runner: 
  flutter_gen_runner: ^3.0.2
```

**Comment by LeonardoRosaa** [comment]
I'm facing this issue with the Flutter 3.19.5.

**Comment by Hackmodford** [comment]
I'm facing this issue with Flutter `3.22.0`, I had to revert back to `3.19.1`
