### ISSUE TITLE
[FR]: Path to directory

### ISSUE THREAD

**Issue by Zalezny** [FlutterGen/flutter_gen#588]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

Missing get path of directory

### Describe the solution

Good solution will be add 'path' variable
For declared asset directory in pubspec.yaml:
    -assets/fonts/

And for gen code:
`Assets.fonts.path` return String path 'assets/fonts'

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AlexV525** [comment]
What is the use case of getting the directory?

**Comment by Zalezny** [comment]
This can be particularly useful when working with groups of assets, for example init easy localization:
```
EasyLocalization(
      supportedLocales: [Locale('en', 'US'), Locale('de', 'DE')],
      path: 'assets/translations', // <-- path
      fallbackLocale: Locale('en', 'US'),
      child: MyApp()
    ),
```

**Comment by AlexV525** [comment]
Is the initialization only happened once?

**Comment by AlexV525** [comment]
Generate paths for assets directories are available through `directory_path_enabled`. See https://github.com/FlutterGen/flutter_gen?tab=readme-ov-file#generate-directories-path

Other variables are not fit in this case.
