### ISSUE TITLE
[Feature Request] Handling duplicate file names

### ISSUE THREAD

**Issue by orestesgaolin** [FlutterGen/flutter_gen#59]
Sometimes it happens that for compatibility I need to use .png and .svg file with the same name e.g. `splash.svg` and `splash.png`. 

It would be awesome to automatically generate different field names for these files e.g. `splash_svg` and `splash_png`.

**Comment by lcdsmao** [comment]
In the next release, if files have the same base name but the different extension will be handled properly.
For example:
https://github.com/FlutterGen/flutter_gen/blob/33e0a6c8377d37d7d365e0da455d02610546bdd0/test_resources/actual_data/assets_camel_case.gen.dart#L24-L27
