### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by xupengku123** [FlutterGen/flutter_gen#595]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Command type

build_runner (Default)

### What happened?

When there are multiple folders in my assets/images directory, such as assets/images/order and assets/images/mine, and each folder contains images, the generated assets_gen.dart file does have classes corresponding to each folder. However, there are no static variables for these classes in the Assets class

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xupengku123** [comment]
<img width="195" alt="企业微信截图_1730102502485" src="https://github.com/user-attachments/assets/86bded7d-47ae-460a-9150-d6afef46a05d">
<img width="344" alt="企业微信截图_17301025163183" src="https://github.com/user-attachments/assets/9da3c928-0e70-42bd-8967-d7db4d593653">
<img width="245" alt="企业微信截图_17301025284751" src="https://github.com/user-attachments/assets/db916296-69ce-4139-9de8-36be74ab792e">

**Comment by xupengku123** [comment]
Can you understand what I mean?

**Comment by AlexV525** [comment]
你可以用中文描述
