### ISSUE TITLE
[FR]: Support I18n language folder

### ISSUE THREAD

**Issue by suifengczc** [FlutterGen/flutter_gen#611]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

My app has i18n design, and some image resources exist in different language folders with the same name in the project because of the existence of text. Is it possible to add a function so that the generated Image Class can automatically access the resources in the corresponding language directory according to locale?
The picture resource folder is as follows：
<img width="336" alt="Snipaste_2024-12-09_00-58-54" src="https://github.com/user-attachments/assets/531ad232-0045-4ec4-b4fd-919281dedf33">
now here is my solution:
``` dart
  String _cardImagePath() {
    switch (I18n.languageCode) {
      case "ja":
        return Assets.ja.images.diagnose.iconDiagnoseGuideTipsBgJa.path;
      case "de":
        return Assets.de.images.diagnose.iconDiagnoseGuideTipsBgDe.path;
      case "fr":
        return Assets.fr.images.diagnose.iconDiagnoseGuideTipsBgFr.path;
      case "pt":
        return Assets.pt.images.diagnose.iconDiagnoseGuideTipsBgPt.path;
      default:
        return Assets.images.diagnose.iconDiagnoseGuideTipsBg.path;
    }
  }
```
but obviously that's not elegant enough,  and as resources increase, many similar codes will be added everywhere.

### Describe the solution

Is it possible to add a function so that the generated Image Class can automatically access the resources in the corresponding language directory according to locale?
I think you can refer to the resource management method in Android Studio. Create resource folders in corresponding language as follows: 
<img width="343" alt="Snipaste_2024-12-09_01-16-36" src="https://github.com/user-attachments/assets/0434be9d-f845-4d18-8b77-7e8912564d09">
then use like Assets.images.diagnose.iconDiagnoseGuideTipsBg to the right language image .

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AlexV525** [comment]
This is mostly based on your localization implementation. There is no general solution for related requests.
