### ISSUE TITLE
Doesn't generate assets.gen.dart when there are no assets.

### ISSUE THREAD

**Issue by WezSieTato** [FlutterGen/flutter_gen#74]
I have an app where I use flutter_gen for working with fonts and are no assets. It would be nice to not generate the empty `Assets` class in such cases. At least parameters like `generate_assets`, `generate_fonts` with true at default in the yaml file will be great.

**Comment by lcdsmao** [comment]
In the next release, we can disable generate assets via:
```
flutter_gen:
  assets:
    enabled: false
```
🙂
